name: Build and Release Solana Lite RPC Storage Ingestor

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y software-properties-common cmake build-essential libclang-dev libudev-dev libssl-dev libsasl2-dev

      - name: Install Rust 1.84.0
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.84.0

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: cargo-${{ runner.os }}-rust-1.84.0-${{ hashFiles('**/Cargo.lock') }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build all crates once
        run: cargo build --release

#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        run: |
#          docker build -t dexterlaboss/ingestor-kafka:${GITHUB_REF_NAME} .
#          docker push dexterlaboss/ingestor-kafka:${GITHUB_REF_NAME}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: 'Release of version ${{ github.ref }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish solana-storage-utils to crates.io
        run: cargo publish -p solana-storage-utils --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish dexter-storage-proto to crates.io
        run: cargo publish -p dexter-storage-proto --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish solana-storage-reader to crates.io
        run: cargo publish -p solana-storage-reader --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish solana-storage-writer to crates.io
        run: cargo publish -p solana-storage-writer --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish solana-hbase-reader to crates.io
        run: cargo publish -p solana-hbase-reader --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish solana-hbase-writer to crates.io
        run: cargo publish -p solana-hbase-writer --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish solana-block-decoder to crates.io
        run: cargo publish -p solana-block-decoder --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
